function [fitresult, gof] = createStepResponseFit(t, vel)
%CREATEFIT(T,V_MEAN)
%  Create a fit.
%
%  Data for 'VStepResponse' fit:
%      X Input : t
%      Y Output: V_mean
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 02-Mar-2023 10:36:39


%% Fit: 'VStepResponse'.
[xData, yData] = prepareCurveData( t, vel );

% Set up fittype and options.
ft = fittype( '300*K*(1-exp(-x/tau))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.913375856139019 0.0975404049994095];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'VStepResponse' );
h = plot( fitresult, xData, yData );
legend( h, 'V_mean vs. t', 'VStepResponse', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't', 'Interpreter', 'none' );
ylabel( 'V_mean', 'Interpreter', 'none' );
grid on


